nmap <leader>p :ProjectList<CR>
nmap <leader>pf :ProjectSearchFiles<CR>
nmap <leader>pc :ProjectFindInFiles<CR>
nmap <leader>pr :ProjectRun<CR>
nmap <leader>pq :ProjectQuit<CR>
nmap <leader>pgc :ProjectGitCommit<CR>
nmap <leader>pgb :ProjectGitBranch<CR>
nmap <leader>pgs :ProjectGitStatus<CR>
nmap <leader>pgh :ProjectGitFileHistory<CR>
